package com.pkb.entities.enums;

public enum MapType {
    NONE, // need this option for the EHRField annotation default value (can't default to null)
    LOINC, LOINC_MAPPING, MEASUREMENT_TYPE, SYMPTOM, SEVERITY, DIAGNOSIS, ALLERGEN, MEDICATION, PROCEDURE,
    OBSERVATION, MESSAGE_TYPE, CLINICAL_RESOURCE, ENCOUNTER_REASON,
    SPECIALITY, CONSENT_GRANT_REASON, RELATIONSHIP, ROLE,
    ALLERGEN_CODED, ALLERGY_DISORDER_CODED,
    DIAGNOSIS_CODED,
    MEDICATION_CODED
}
